# Generated by Django 5.1.5 on 2025-02-13 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('Jno', models.IntegerField(primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=50)),
                ('runs', models.IntegerField()),
                ('wickets', models.IntegerField()),
                ('tname', models.CharField(max_length=50)),
            ],
        ),
    ]
